channels:
  - r
  - defaults
  - conda-forge
dependencies:
  - webdataset
  - nibabel
  - tqdm
  - pynvml
  - setuptools
  - nilearn
  - numpy
  - scikit-learn
  - simple-parsing
  - sentencepiece
  - lightning
  - pybids
  - einops
  - wandb
  - conda-content-trust
  - ipywidgets
  - wheel
  - pyparsing
  - huggingface::transformers
  - huggingface::datasets
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - python=3.10
  - pip
  - git
  - pip: 
    - datalad-installer
