channels:
  - r
  - nvidia
  - pytorch
  - defaults
dependencies:
  - datalad
  - einops
  - conda-forge::datasets
  - conda-forge::transformers == 4.31.*
  - conda-forge::tokenizers => 0.13.3
  - conda-forge::torchmetrics
  - ipywidgets
  - lightning
  - nibabel
  - nilearn
  - numpy==1.25.*
  - pybids
  - pynvml
  - pyparsing
  - pytorch::pytorch == 2.0.*
  - pytorch::torchaudio
  - pytorch::torchvision
  - torchmetrics
  - scikit-learn
  - sentencepiece
  - setuptools
  - simple-parsing
  - tqdm
  - wandb
  - webdataset
  - wheel
  - python=3.10
  - pip
  - git
  - make
  - pytorch-cuda>=11.7
