channels:
  - r
  - defaults
  - conda-forge
dependencies:
  - datalad
  - einops
  - conda-forge::datasets
  - conda-forge::transformers
  - conda-forge::tokenizers=>0.13.3
  - ipywidgets
  - lightning
  - nibabel
  - nilearn
  - numpy
  - pybids
  - pynvml
  - pyparsing
  - pytorch::pytorch=2.0.*
  - pytorch::torchaudio
  - pytorch::torchvision
  - scikit-learn
  - sentencepiece
  - setuptools
  - simple-parsing
  - tqdm
  - wandb
  - webdataset
  - wheel
  - python=3.10
  - pip
  - git
  - make
