name: moralLM
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - pytorch=1.12.1
  - torchaudio
  - torchvision
  - cudatoolkit=11.3
  - pip=23.0.1
  - pip:
    - transformers[sentencepiece]
    - scikit-learn
    - pandas
    - lightning